### ISSUE TITLE
Failed building ddcutil: ddc_services.c:(.text+0x20a): undefined reference to `init_usb_display's'

### ISSUE THREAD

**Issue by lwilletts** [rockowitz/ddcutil#101]
Hi, I believe I am missing a package to fully build ddcutil, but having a look at the building from source page shows me that I have all the requisite packages installed on my Arch system. I haven't seen anyone else report this problem so it's probably something I'm doing, thanks.

```
make[3]: Entering directory '/home/fyr/.cache/yay/ddcutil-git/src/ddcutil/src'
  CCLD     libapp.la
  CCLD     libcommon.la
Executing hook all-local...
  CC       app_ddcutil/ddcutil-main.o
  CC       app_ddcutil/ddcutil-app_dynamic_features.o
  CC       app_ddcutil/ddcutil-app_vcp_info.o
  CC       app_ddcutil/ddcutil-app_dumpload.o
  CC       app_ddcutil/ddcutil-app_setvcp.o
  CC       app_ddcutil/ddcutil-app_getvcp.o
  CCLD     ddcutil
/bin/ld: ./.libs/libcommon.a(ddc_services.o): in function `init_ddc_services':
ddc_services.c:(.text+0x20a): undefined reference to `init_usb_displays'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:885: ddcutil] Error 1
make[3]: Leaving directory '/home/fyr/.cache/yay/ddcutil-git/src/ddcutil/src'
make[2]: *** [Makefile:1132: all-recursive] Error 1
make[2]: Leaving directory '/home/fyr/.cache/yay/ddcutil-git/src/ddcutil/src'
make[1]: *** [Makefile:577: all-recursive] Error 1
make[1]: Leaving directory '/home/fyr/.cache/yay/ddcutil-git/src/ddcutil'
make: *** [Makefile:484: all] Error 2
```

**Comment by rockowitz** [comment]
First, are you building from source or using the Arch package?

The configure command should complain about missing packages. Keep in 
mind that if the "missing" package is XXX, what is probably needed is 
actually XXX-dev  or XXX-devel, depending on distribution.  (Such is the 
behavior of pkg-config.)

If there's a required package that configure is not checking for, then 
compilation should reveal the missing header file, which in turn implies 
the package.  If the solution is not apparent, send me the compiler 
error messages.

In any event, please report the missing package, once the solution is found.

Finally, a wild stab in the dark.  The Debian folks recently pointed out 
that package hwdata needs to be specifically required on that distribution.

Sanford

**Comment by lwilletts** [comment]
I'm using the ddcutil-git package, which is a source build. The build doesn't fail at configure, so it's happy enough that the build can proceed. Looking over the compilation I can't see anything obvious, here's the full build log: http://ix.io/261G

hwdata doesn't seem to be a package on arch, so I don't know what it provides on debian.

**Comment by rockowitz** [comment]
The problem occurs at link time because usb support is disabled (so usb 
related files are not compiled), yet there's a reference to a function 
in one of those files.  This may be related to the configure errors, 
which is surprising since that portion of the configure script has been 
untouched for years.  Perhaps is something particular about Arch.   What 
command shell are you using?  Is it something other than bash?  Please 
send me the generated configure script.

As a workaround, you might try executing "configure --enable-usb" to 
explicitly enable usb support.  This may get you past the problem while 
I figure out what is going on.

Package hwdata supplies files usb.ids, pci.ids and pnp.ids.  Any normal 
Linux distribution will install these files.  They're peculiar in that 
they are provided by multiple packages, so there can be multiple copies 
installed in different directories.

**Comment by rockowitz** [comment]
A fix for the link failure has been pushed to branch 0.9.9-dev.

I still would like to see the generated configure file to try to 
understand why we're getting the configure errors.

**Comment by lwilletts** [comment]
Can confirm the commit in 0.9.9-dev has fixed the issue for me. Here's the configure file that gets generated: http://ix.io/26kw

**Comment by rockowitz** [comment]
What command shell are you using?

**Comment by lwilletts** [comment]
zsh

**Comment by rockowitz** [comment]
Thanks.  Looks like it's a bashism in the configure script.  (Using "==" 
as a synonym for "=".)  I'll fix.

**Comment by rockowitz** [comment]
I've pushed an updated configure.ac file to branch 0.9.9-dev.  This 
version replaces use of "==" for string equality testing with "=".  The 
double equal sign is a bash alias for "=", and is not necessarily 
present on other shells. (In zsh it's definition is controlled by the 
setopt option EQUALS.)

Please run autoconf on the updated configure.ac, run the generated 
configure file (the error messages should be gone), and send me the 
output so that I can check.  Thank you.

- Sanford

**Comment by lwilletts** [comment]
Hi, here's the new generated configure output when run: http://ix.io/26v0

Can confirm no issues building.

**Comment by rockowitz** [comment]
I'm going to close this issue as the two problems both appear to be 
resolved.

Regards,
Sanford
