### ISSUE TITLE
Question. LineageOS Android Raspberry Pi

### ISSUE THREAD

**Issue by flesti** [rockowitz/ddcutil#232]
Wondering if ddcutil can be ported to Android, Maybe through Termux or something, since the I2C works on [LineageOS ](https://konstakang.com/devices/rpi4/LineageOS18/)on Raspberry.

**Comment by rockowitz** [comment]
The first question will be whether the video drivers support I2C.  The Pi drivers do.  Whether the LineageOS drivers do would have to be checked. 

More generally, the question is whether LineageOS provides all of the Linux API services that ddcutil uses, and if not then what workarounds are possible.  To get a sense of how extensive the changes might be, you might want to look through the ddcutil source for all the changes that had to be made to build ddcutil on BSD.  (Look for the TARGET_BSD iftests.) In the end the BSD port was put on hold because BSD video drivers turned out not to support I2C.
