### ISSUE TITLE
Cintiq 27QHDT not responding to some DDC commands

### ISSUE THREAD

**Issue by Kirtai** [rockowitz/ddcutil#62]
I have a Wacom Cintiq 27QHDT that has no physical controls. Using ddcutil I can operate some things, like the brightness/contrast/reset etc, but the colour settings refuse to budge.

- Feature: 14 (Select color preset) does change but returns a "Null response" error and is unable to format the output.
- The colour Features 16, 18, 1a (RGB gain) 59,5a,5b,5c,5d,5e (6 axis saturation), 8a,(colour saturation) ,90 (hue) and 9b,9c,9d,9e,9f,a0 (6 axis hue) are all readable but cannot be changed by using setvcp. The only error given is "Verification failed for feature X"

I can't see any other colour adjustment features.

I would really like to get this working fully under Linux.
Attached are the probe, interrogate and capabilities reports.
(I have three monitors but didn't remove those details from the reports since I don't know what's useful)

[ddc-27qhd-capabilities.txt](https://github.com/rockowitz/ddcutil/files/2481357/ddc-27qhd-capabilities.txt)
[ddc-27qhd-interrogate.txt](https://github.com/rockowitz/ddcutil/files/2481358/ddc-27qhd-interrogate.txt)
[ddc-27qhd-probe.txt](https://github.com/rockowitz/ddcutil/files/2481359/ddc-27qhd-probe.txt)

**Comment by rockowitz** [comment]
I'm afraid I have little good news for you.  DDC implementations are 
problematic.

More specifically:
- The DDC VCP Set command (command code x02) has no mechanism for 
determining success.  All it does is put some bytes on the I2C bus and 
trust that the monitor will handle them.  That's why, by default, 
ddcutil reads a feature value after writing it to test success.
- On some monitors, e.g. the Dell U3011 in front of  me, you can see the 
effect from, for example, changing the red gain, but the reading the 
value will show no change.
- Conversely, I've seen cases where the new value read by ddcutil has 
changed correctly, but there's no apparent change to the monitor.
- The availability of some features can be mode dependent.  Again, on 
the U3011, changes to the saturation and hue values affect the image 
only if the monitor is set to take input in YPbPr mode as opposed to RGB.
Some color related features can be changed only if the Color Preset 
(feature x14) or Display Application (feature xDC) is set to user defined.
- I also note that the capabilities command reports an undocumented 
command code (xF0), and a large number of manufacturer specific features.

- The DDC Null message is actually a valid response to getvcp i.e. a VCP 
Request (x01), VCP Response (x02) sequence.  It contains no data to 
format. Per the DDC/CI spec:

The NULL message is used in the following cases:
- To detect that the display is DDC/CI capable (by reading it at 0x6Fh 
I2C slave address)
- To tell the host that display does not have any answer to give the 
host (not ready or not expected)
- The "Enable Application Report" has not been sent before using 
Application Messages.

The second point is really a catch-all.  Some monitors use a Null 
Message to indicate an unsupported feature (as opposed to setting the 
Unsupported VCP Code flag in a normal getvcp response.

So I'm afraid that, absent DDC documentation from Wacom, you're left 
with experimenting to see what works when.

Sanford
