### ISSUE TITLE
eizo EV2785

### ISSUE THREAD

**Issue by yannick** [rockowitz/ddcutil#68]
seems to not work.
here is a interrogate
https://gist.github.com/yannick/cfb5440a8ecc5bfb6cec8c7fae2f5036

also i did some usb sniffing in windows, this one first shows the internal eizo identification menu and then does some gamma/brightness calibration stuff
https://gist.github.com/yannick/c61294e474598d849a46aa996c41a9d1

the usb features as detected by usblyzer:
https://gist.github.com/yannick/28959ee9f1ad2e07b6c2583d021a43bb

**Comment by yannick** [comment]
hi @rockowitz  
no worries, and thanks for prividing a great tool!
here is the output:
https://gist.github.com/d3bc454d90de8a5e39f55869b9a4d961

**Comment by rockowitz** [comment]
The output confirms that the Eizo is using a private "usage page" for 
its USB reports, instead of those defined in the spec.  It might be 
possible to reverse engineer the Eizo reports using usblyzer on Windows, 
but that would be a lot of work and might possibly run afoul of 
licensing issues.

Regards,
Sanford
